version: '3'

services:
  # Контейнер для Flask
  flask_app:
    build: ./Server
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: server_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1
    depends_on:
      - db
    expose:
      - 5000

  # Контейнер для PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: server_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1
    volumes:
#      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  # Контейнер для Nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - flask_app

volumes:
  pgdata:
